//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 32 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: 확인
      ///
      /// Key: common_confirm
      ///
      /// Locales: en
      var common_confirm: RswiftResources.StringResource { .init(key: "common_confirm", tableName: "Localizable", source: source, developmentValue: "확인", comment: nil) }

      /// en translation: 다음
      ///
      /// Key: common_next
      ///
      /// Locales: en
      var common_next: RswiftResources.StringResource { .init(key: "common_next", tableName: "Localizable", source: source, developmentValue: "다음", comment: nil) }

      /// en translation: 완료
      ///
      /// Key: complete_text
      ///
      /// Locales: en
      var complete_text: RswiftResources.StringResource { .init(key: "complete_text", tableName: "Localizable", source: source, developmentValue: "완료", comment: nil) }

      /// en translation: 내용을 입력하세요
      ///
      /// Key: diary_edit_text
      ///
      /// Locales: en
      var diary_edit_text: RswiftResources.StringResource { .init(key: "diary_edit_text", tableName: "Localizable", source: source, developmentValue: "내용을 입력하세요", comment: nil) }

      /// en translation: 일기 쓰기
      ///
      /// Key: diary_note
      ///
      /// Locales: en
      var diary_note: RswiftResources.StringResource { .init(key: "diary_note", tableName: "Localizable", source: source, developmentValue: "일기 쓰기", comment: nil) }

      /// en translation:  장소, 주소를 입력해주세요
      ///
      /// Key: diary_place_address_title
      ///
      /// Locales: en
      var diary_place_address_title: RswiftResources.StringResource { .init(key: "diary_place_address_title", tableName: "Localizable", source: source, developmentValue: " 장소, 주소를 입력해주세요", comment: nil) }

      /// en translation: 장소 선택
      ///
      /// Key: diary_select_place
      ///
      /// Locales: en
      var diary_select_place: RswiftResources.StringResource { .init(key: "diary_select_place", tableName: "Localizable", source: source, developmentValue: "장소 선택", comment: nil) }

      /// en translation: 제목
      ///
      /// Key: diary_title
      ///
      /// Locales: en
      var diary_title: RswiftResources.StringResource { .init(key: "diary_title", tableName: "Localizable", source: source, developmentValue: "제목", comment: nil) }

      /// en translation: 캘린더
      ///
      /// Key: main_tab_calendar
      ///
      /// Locales: en
      var main_tab_calendar: RswiftResources.StringResource { .init(key: "main_tab_calendar", tableName: "Localizable", source: source, developmentValue: "캘린더", comment: nil) }

      /// en translation: 홈
      ///
      /// Key: main_tab_home
      ///
      /// Locales: en
      var main_tab_home: RswiftResources.StringResource { .init(key: "main_tab_home", tableName: "Localizable", source: source, developmentValue: "홈", comment: nil) }

      /// en translation: 마이페이지
      ///
      /// Key: main_tab_my_page
      ///
      /// Locales: en
      var main_tab_my_page: RswiftResources.StringResource { .init(key: "main_tab_my_page", tableName: "Localizable", source: source, developmentValue: "마이페이지", comment: nil) }

      /// en translation: 일기 작성
      ///
      /// Key: main_tab_note
      ///
      /// Locales: en
      var main_tab_note: RswiftResources.StringResource { .init(key: "main_tab_note", tableName: "Localizable", source: source, developmentValue: "일기 작성", comment: nil) }

      /// en translation: 러브버드가 잊지않고 챙겨드릴게요
      ///
      /// Key: onboarding_birthdate_description
      ///
      /// Locales: en
      var onboarding_birthdate_description: RswiftResources.StringResource { .init(key: "onboarding_birthdate_description", tableName: "Localizable", source: source, developmentValue: "러브버드가 잊지않고 챙겨드릴게요", comment: nil) }

      /// en translation: 생년월일을 알려주세요
      ///
      /// Key: onboarding_birthdate_title
      ///
      /// Locales: en
      var onboarding_birthdate_title: RswiftResources.StringResource { .init(key: "onboarding_birthdate_title", tableName: "Localizable", source: source, developmentValue: "생년월일을 알려주세요", comment: nil) }

      /// en translation: 러브버드가 기념일을 계산해서 알려드릴게요
      ///
      /// Key: onboarding_date_description
      ///
      /// Locales: en
      var onboarding_date_description: RswiftResources.StringResource { .init(key: "onboarding_date_description", tableName: "Localizable", source: source, developmentValue: "러브버드가 기념일을 계산해서 알려드릴게요", comment: nil) }

      /// en translation: 초기화
      ///
      /// Key: onboarding_date_initial
      ///
      /// Locales: en
      var onboarding_date_initial: RswiftResources.StringResource { .init(key: "onboarding_date_initial", tableName: "Localizable", source: source, developmentValue: "초기화", comment: nil) }

      /// en translation: 연인과 사랑을 시작한 날짜를 알려주세요
      ///
      /// Key: onboarding_date_title
      ///
      /// Locales: en
      var onboarding_date_title: RswiftResources.StringResource { .init(key: "onboarding_date_title", tableName: "Localizable", source: source, developmentValue: "연인과 사랑을 시작한 날짜를 알려주세요", comment: nil) }

      /// en translation: 서비스 관련 안내 및 계정 구분을 위해 사용돼요!
      ///
      /// Key: onboarding_email_description
      ///
      /// Locales: en
      var onboarding_email_description: RswiftResources.StringResource { .init(key: "onboarding_email_description", tableName: "Localizable", source: source, developmentValue: "서비스 관련 안내 및 계정 구분을 위해 사용돼요!", comment: nil) }

      /// en translation: 러브버드에서 사용할 이메일을 알려주세요
      ///
      /// Key: onboarding_email_title
      ///
      /// Locales: en
      var onboarding_email_title: RswiftResources.StringResource { .init(key: "onboarding_email_title", tableName: "Localizable", source: source, developmentValue: "러브버드에서 사용할 이메일을 알려주세요", comment: nil) }

      /// en translation: 원하시지 않는다면 비공개를 선택하실 수 있어요
      ///
      /// Key: onboarding_gender_description
      ///
      /// Locales: en
      var onboarding_gender_description: RswiftResources.StringResource { .init(key: "onboarding_gender_description", tableName: "Localizable", source: source, developmentValue: "원하시지 않는다면 비공개를 선택하실 수 있어요", comment: nil) }

      /// en translation: 여성
      ///
      /// Key: onboarding_gender_female
      ///
      /// Locales: en
      var onboarding_gender_female: RswiftResources.StringResource { .init(key: "onboarding_gender_female", tableName: "Localizable", source: source, developmentValue: "여성", comment: nil) }

      /// en translation: 남성
      ///
      /// Key: onboarding_gender_male
      ///
      /// Locales: en
      var onboarding_gender_male: RswiftResources.StringResource { .init(key: "onboarding_gender_male", tableName: "Localizable", source: source, developmentValue: "남성", comment: nil) }

      /// en translation: 비공개
      ///
      /// Key: onboarding_gender_private
      ///
      /// Locales: en
      var onboarding_gender_private: RswiftResources.StringResource { .init(key: "onboarding_gender_private", tableName: "Localizable", source: source, developmentValue: "비공개", comment: nil) }

      /// en translation: 당신의 성별을 알려주세요
      ///
      /// Key: onboarding_gender_title
      ///
      /// Locales: en
      var onboarding_gender_title: RswiftResources.StringResource { .init(key: "onboarding_gender_title", tableName: "Localizable", source: source, developmentValue: "당신의 성별을 알려주세요", comment: nil) }

      /// en translation: 초대코드를 공유해 연인과 러브버드를 연결하세요
      ///
      /// Key: onboarding_invitation_description
      ///
      /// Locales: en
      var onboarding_invitation_description: RswiftResources.StringResource { .init(key: "onboarding_invitation_description", tableName: "Localizable", source: source, developmentValue: "초대코드를 공유해 연인과 러브버드를 연결하세요", comment: nil) }

      /// en translation: 초대코드 입력
      ///
      /// Key: onboarding_invitation_input
      ///
      /// Locales: en
      var onboarding_invitation_input: RswiftResources.StringResource { .init(key: "onboarding_invitation_input", tableName: "Localizable", source: source, developmentValue: "초대코드 입력", comment: nil) }

      /// en translation: 전달받은 초대코드가 있으신가요?
      ///
      /// Key: onboarding_invitation_question
      ///
      /// Locales: en
      var onboarding_invitation_question: RswiftResources.StringResource { .init(key: "onboarding_invitation_question", tableName: "Localizable", source: source, developmentValue: "전달받은 초대코드가 있으신가요?", comment: nil) }

      /// en translation: 러브버드를 연인에게 보내보세요
      ///
      /// Key: onboarding_invitation_title
      ///
      /// Locales: en
      var onboarding_invitation_title: RswiftResources.StringResource { .init(key: "onboarding_invitation_title", tableName: "Localizable", source: source, developmentValue: "러브버드를 연인에게 보내보세요", comment: nil) }

      /// en translation: 애칭이 없다면 이름 또는 별명을 알려주셔도 좋아요
      ///
      /// Key: onboarding_nickname_description
      ///
      /// Locales: en
      var onboarding_nickname_description: RswiftResources.StringResource { .init(key: "onboarding_nickname_description", tableName: "Localizable", source: source, developmentValue: "애칭이 없다면 이름 또는 별명을 알려주셔도 좋아요", comment: nil) }

      /// en translation: 당신의 애칭을 알려주세요
      ///
      /// Key: onboarding_nickname_title
      ///
      /// Locales: en
      var onboarding_nickname_title: RswiftResources.StringResource { .init(key: "onboarding_nickname_title", tableName: "Localizable", source: source, developmentValue: "당신의 애칭을 알려주세요", comment: nil) }

      /// en translation: 설정하신 프로필 이미지는 상대 러버가 볼 수 있어요
      ///
      /// Key: onboarding_profile_description
      ///
      /// Locales: en
      var onboarding_profile_description: RswiftResources.StringResource { .init(key: "onboarding_profile_description", tableName: "Localizable", source: source, developmentValue: "설정하신 프로필 이미지는 상대 러버가 볼 수 있어요", comment: nil) }

      /// en translation: 프로필 이미지를 설정해주세요
      ///
      /// Key: onboarding_profile_title
      ///
      /// Locales: en
      var onboarding_profile_title: RswiftResources.StringResource { .init(key: "onboarding_profile_title", tableName: "Localizable", source: source, developmentValue: "프로필 이미지를 설정해주세요", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 21 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `Error`.
    var error: RswiftResources.ColorResource { .init(name: "Error", path: [], bundle: bundle) }

    /// Color `Gray01`.
    var gray01: RswiftResources.ColorResource { .init(name: "Gray01", path: [], bundle: bundle) }

    /// Color `Gray02`.
    var gray02: RswiftResources.ColorResource { .init(name: "Gray02", path: [], bundle: bundle) }

    /// Color `Gray03`.
    var gray03: RswiftResources.ColorResource { .init(name: "Gray03", path: [], bundle: bundle) }

    /// Color `Gray04`.
    var gray04: RswiftResources.ColorResource { .init(name: "Gray04", path: [], bundle: bundle) }

    /// Color `Gray05`.
    var gray05: RswiftResources.ColorResource { .init(name: "Gray05", path: [], bundle: bundle) }

    /// Color `Gray06`.
    var gray06: RswiftResources.ColorResource { .init(name: "Gray06", path: [], bundle: bundle) }

    /// Color `Gray07`.
    var gray07: RswiftResources.ColorResource { .init(name: "Gray07", path: [], bundle: bundle) }

    /// Color `Gray08`.
    var gray08: RswiftResources.ColorResource { .init(name: "Gray08", path: [], bundle: bundle) }

    /// Color `Gray09`.
    var gray09: RswiftResources.ColorResource { .init(name: "Gray09", path: [], bundle: bundle) }

    /// Color `Gray10`.
    var gray10: RswiftResources.ColorResource { .init(name: "Gray10", path: [], bundle: bundle) }

    /// Color `Gray11`.
    var gray11: RswiftResources.ColorResource { .init(name: "Gray11", path: [], bundle: bundle) }

    /// Color `Gray115`.
    var gray115: RswiftResources.ColorResource { .init(name: "Gray115", path: [], bundle: bundle) }

    /// Color `Gray12`.
    var gray12: RswiftResources.ColorResource { .init(name: "Gray12", path: [], bundle: bundle) }

    /// Color `Gray122`.
    var gray122: RswiftResources.ColorResource { .init(name: "Gray122", path: [], bundle: bundle) }

    /// Color `Gray231`.
    var gray231: RswiftResources.ColorResource { .init(name: "Gray231", path: [], bundle: bundle) }

    /// Color `Green100`.
    var green100: RswiftResources.ColorResource { .init(name: "Green100", path: [], bundle: bundle) }

    /// Color `Pink255`.
    var pink255: RswiftResources.ColorResource { .init(name: "Pink255", path: [], bundle: bundle) }

    /// Color `Primary`.
    var primary: RswiftResources.ColorResource { .init(name: "Primary", path: [], bundle: bundle) }

    /// Color `Secondary`.
    var secondary: RswiftResources.ColorResource { .init(name: "Secondary", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 21 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `ic_back`.
    var ic_back: RswiftResources.ImageResource { .init(name: "ic_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_calendar`.
    var ic_calendar: RswiftResources.ImageResource { .init(name: "ic_calendar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_list_bulleted`.
    var ic_list_bulleted: RswiftResources.ImageResource { .init(name: "ic_list_bulleted", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_map`.
    var ic_map: RswiftResources.ImageResource { .init(name: "ic_map", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_navigate_next`.
    var ic_navigate_next: RswiftResources.ImageResource { .init(name: "ic_navigate_next", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_navigate_next_active`.
    var ic_navigate_next_active: RswiftResources.ImageResource { .init(name: "ic_navigate_next_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_navigate_next_inactive`.
    var ic_navigate_next_inactive: RswiftResources.ImageResource { .init(name: "ic_navigate_next_inactive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_navigate_previous_active`.
    var ic_navigate_previous_active: RswiftResources.ImageResource { .init(name: "ic_navigate_previous_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_navigate_previous_inactive`.
    var ic_navigate_previous_inactive: RswiftResources.ImageResource { .init(name: "ic_navigate_previous_inactive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_note`.
    var ic_note: RswiftResources.ImageResource { .init(name: "ic_note", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_notification`.
    var ic_notification: RswiftResources.ImageResource { .init(name: "ic_notification", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_person`.
    var ic_person: RswiftResources.ImageResource { .init(name: "ic_person", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_place`.
    var ic_place: RswiftResources.ImageResource { .init(name: "ic_place", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_profile`.
    var ic_profile: RswiftResources.ImageResource { .init(name: "ic_profile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_search`.
    var ic_search: RswiftResources.ImageResource { .init(name: "ic_search", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_timeline`.
    var ic_timeline: RswiftResources.ImageResource { .init(name: "ic_timeline", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_appleLogin`.
    var img_appleLogin: RswiftResources.ImageResource { .init(name: "img_appleLogin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_backHeart`.
    var img_backHeart: RswiftResources.ImageResource { .init(name: "img_backHeart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_googleLogin`.
    var img_googleLogin: RswiftResources.ImageResource { .init(name: "img_googleLogin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_kakaoLogin`.
    var img_kakaoLogin: RswiftResources.ImageResource { .init(name: "img_kakaoLogin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_naverLogin`.
    var img_naverLogin: RswiftResources.ImageResource { .init(name: "img_naverLogin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let apsEnvironment: String = "development"
  }

  /// This `_R.font` struct is generated, and contains static references to 6 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `GmarketSansBold`.
    var gmarketSansBold: RswiftResources.FontResource { .init(name: "GmarketSansBold", bundle: bundle, filename: "GmarketSansBold.otf") }

    /// Font `GmarketSansLight`.
    var gmarketSansLight: RswiftResources.FontResource { .init(name: "GmarketSansLight", bundle: bundle, filename: "GmarketSansLight.otf") }

    /// Font `GmarketSansMedium`.
    var gmarketSansMedium: RswiftResources.FontResource { .init(name: "GmarketSansMedium", bundle: bundle, filename: "GmarketSansMedium.otf") }

    /// Font `Pretendard-Bold`.
    var pretendardBold: RswiftResources.FontResource { .init(name: "Pretendard-Bold", bundle: bundle, filename: "Pretendard-Bold.otf") }

    /// Font `Pretendard-Regular`.
    var pretendardRegular: RswiftResources.FontResource { .init(name: "Pretendard-Regular", bundle: bundle, filename: "Pretendard-Regular.otf") }

    /// Font `Pretendard-SemiBold`.
    var pretendardSemiBold: RswiftResources.FontResource { .init(name: "Pretendard-SemiBold", bundle: bundle, filename: "Pretendard-SemiBold.otf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [gmarketSansBold, gmarketSansLight, gmarketSansMedium, pretendardBold, pretendardRegular, pretendardSemiBold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 7 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GmarketSansBold.otf`.
    var gmarketSansBoldOtf: RswiftResources.FileResource { .init(name: "GmarketSansBold", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `GmarketSansLight.otf`.
    var gmarketSansLightOtf: RswiftResources.FileResource { .init(name: "GmarketSansLight", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `GmarketSansMedium.otf`.
    var gmarketSansMediumOtf: RswiftResources.FileResource { .init(name: "GmarketSansMedium", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Pretendard-Bold.otf`.
    var pretendardBoldOtf: RswiftResources.FileResource { .init(name: "Pretendard-Bold", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Pretendard-Regular.otf`.
    var pretendardRegularOtf: RswiftResources.FileResource { .init(name: "Pretendard-Regular", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Pretendard-SemiBold.otf`.
    var pretendardSemiBoldOtf: RswiftResources.FileResource { .init(name: "Pretendard-SemiBold", pathExtension: "otf", bundle: bundle, locale: LocaleReference.none) }
  }
}